# Generated by Django 5.1.1 on 2024-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.TextField(default='details here'),
            preserve_default=False,
        ),
    ]
